{{- if and .Values.decode.create .Values.multinode }}
apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: {{ include "llm-d-modelservice.decodeName" . }}
  labels:
    {{- include "llm-d-modelservice.labels" . | nindent 4 }}
    {{- include "llm-d-modelservice.decodelabels" . | nindent 4 }}
  annotations:
    leaderworkerset.sigs.k8s.io/subgroup-exclusive-topology: kubernetes.io/hostname
spec:
  {{- if not .Values.decode.autoscaling.enabled }}
  replicas: {{ default 1 .Values.decode.replicas }}
  {{- end }}
  leaderWorkerTemplate:
    size: {{ int (include "llm-d-modelservice.dataParallelism" .Values.decode.parallelism) }}
    {{- if .Values.decode.subGroupPolicy }}
    subGroupPolicy:
    {{- toYaml .Values.decode.subGroupPolicy | nindent 6 }}
    {{- else }}
    subGroupPolicy:
      subGroupSize: 8
    {{-  end }}
    workerTemplate:
      metadata:
        labels:
          {{- include "llm-d-modelservice.decodelabels" . | nindent 10 }}
      spec:
        hostIPC: true
        hostPID: true
        {{- with .Values.routing }}
        {{ (include "llm-d-modelservice.routingProxy" .) | nindent 8 }}
        {{- end }}
        {{- (include "llm-d-modelservice.modelPod" (merge . (dict "pdSpec" .Values.decode))) | nindent 6 }}
        {{- with .Values.decode.containers }}
        containers:
          {{- range . }}
        {{- (include "llm-d-modelservice.container" (merge (dict "role" "decode" "container" . "parallelism" $.Values.decode.parallelism) $)) | nindent 8 }}
          {{- end }}
        {{- end }}
{{- end }}
