{{- if .Values.endpointPicker -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "llm-d-modelservice.fullname" . }}-epp-service
  labels:
    {{- include "llm-d-modelservice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.endpointPicker.service.type }}
  ports:
    - port: {{ .Values.endpointPicker.service.port }}
      targetPort: {{ .Values.endpointPicker.service.targetPort }}
      protocol: TCP
      appProtocol: {{ .Values.endpointPicker.service.appProtocol }}
  selector:
    llm-d.ai/epp: {{ include "llm-d-modelservice.fullname" . }}-epp
{{- end }}
