{{- if .Values.endpointPicker -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "llm-d-modelservice.fullname" . }}-epp
  labels:
    llm-d.ai/epp: {{ include "llm-d-modelservice.fullname" . }}-epp
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      llm-d.ai/epp: {{ include "llm-d-modelservice.fullname" . }}-epp
  template:
    metadata:
      labels:
        llm-d.ai/epp: {{ include "llm-d-modelservice.fullname" . }}-epp
    spec:
      containers:
      - name: epp
        imagePullPolicy: Always
        image: {{ default "ghcr.io/llm-d/llm-d-inference-scheduler:0.0.3" .Values.endpointPicker.image }}
        args:
        - --poolName
        - {{ include "llm-d-modelservice.fullname" . }}-inference-pool
        - --poolNamespace
        - {{ .Release.Namespace }}
        - -v
        - "{{ default 4 .Values.endpointPicker.debugLevel }}"
        - --zap-encoder
        - json
        - --grpcPort
        - "9002"
        - --grpcHealthPort
        - "9003"
        # using defaults from https://github.com/llm-d/llm-d-deployer/blob/main/charts/llm-d/values.yaml#L563-L603
        env:
        - name: ENABLE_KVCACHE_AWARE_SCORER
          value: "false"
        - name: ENABLE_LOAD_AWARE_SCORER
          value: "true"
        - name: ENABLE_PREFIX_AWARE_SCORER
          value: "true"
        - name: ENABLE_SESSION_AWARE_SCORER
          value: "false"
        - name: KVCACHE_AWARE_SCORER_WEIGHT
          value: "1"
        - name: KVCACHE_INDEXER_REDIS_ADDR
        - name: LOAD_AWARE_SCORER_WEIGHT
          value: "1"
        - name: PD_ENABLED
          value: "false"
        - name: PD_PROMPT_LEN_THRESHOLD
          value: "10"
        - name: PREFILL_ENABLE_KVCACHE_AWARE_SCORER
          value: "false"
        - name: PREFILL_ENABLE_LOAD_AWARE_SCORER
          value: "false"
        - name: PREFILL_ENABLE_PREFIX_AWARE_SCORER
          value: "false"
        - name: PREFILL_ENABLE_SESSION_AWARE_SCORER
          value: "false"
        - name: PREFILL_KVCACHE_AWARE_SCORER_WEIGHT
          value: "1"
        - name: PREFILL_KVCACHE_INDEXER_REDIS_ADDR
        - name: PREFILL_LOAD_AWARE_SCORER_WEIGHT
          value: "1"
        - name: PREFILL_PREFIX_AWARE_SCORER_WEIGHT
          value: "1"
        - name: PREFILL_SESSION_AWARE_SCORER_WEIGHT
          value: "1"
        - name: PREFIX_AWARE_SCORER_WEIGHT
          value: "2"
        - name: SESSION_AWARE_SCORER_WEIGHT
          value: "1"
        ports:
        - containerPort: 9002
          name: grpc
          protocol: TCP
        - containerPort: 9003
          name: grpc-health
          protocol: TCP
        - containerPort: 9090
          name: metrics
          protocol: TCP
        {{- if (not .Values.endpointPicker.disableReadinessProbe) }}
        readinessProbe:
          grpc:
            port: 9003
            service: envoy.service.ext_proc.v3.ExternalProcessor
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        {{- end }}
        {{- if (not .Values.endpointPicker.disableLivenessProbe) }}
        livenessProbe:
          grpc:
            port: 9003
            service: envoy.service.ext_proc.v3.ExternalProcessor
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        {{- end }}
      serviceAccount: {{ include "llm-d-modelservice.eppServiceAccountName" . }}
      serviceAccountName: {{ include "llm-d-modelservice.eppServiceAccountName" . }}
{{- end }}
