
{{- if .Values.routing.httpRoute.create }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "llm-d-modelservice.fullname" . }}-http-route
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "llm-d-modelservice.labels" . | nindent 4 }}
spec:
  {{- with .Values.routing.parentRefs }}
  parentRefs:
  {{- . | toYaml | nindent 2}}
  {{- end }}
  rules:
  {{- if .Values.routing.httpRoute.backendRefs }}
  {{- with .Values.routing.httpRoute.backendRefs }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- else }}
  - backendRefs:
    - group: inference.networking.x-k8s.io
      kind: InferencePool
      {{- if .Values.routing.httpRoute.inferencePool }}
      name: {{ .Values.routing.httpRoute.inferencePool }}
      {{- else }}
      name: {{ include "llm-d-modelservice.fullname" . }}-inference-pool
      {{- end }}
      port: {{ .Values.routing.servicePort  }}
      weight: 1
    {{- if .Values.routing.httpRoute.matches }}
    {{- with .Values.routing.httpRoute.matches }}
    matches:
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- else }}
    matches:
    - path:
        type: PathPrefix
        value: /
      headers:
      - name: x-model-name
        type: Exact
        value: {{ .Values.routing.modelName }}
    {{- end }}
  {{- end }}
{{- end }}