{{- if and .Values.prefill.create (not .Values.multinode) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "llm-d-modelservice.prefillName" . }}
  labels:
    {{- include "llm-d-modelservice.labels" . | nindent 4 }}
spec:
  replicas: {{ default 1 .Values.prefill.replicas }}
  selector:
    matchLabels:
      {{- include "llm-d-modelservice.prefilllabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "llm-d-modelservice.prefilllabels" . | nindent 8 }}
    spec:
      {{- (include "llm-d-modelservice.modelPod" (merge . (dict "pdSpec" .Values.prefill))) | nindent 4 }}
      {{- with .Values.prefill.containers }}
      containers:
        {{- range . }}
        {{- (include "llm-d-modelservice.container" (merge (dict "role" "prefill" "container" . "parallelism" $.Values.prefill.parallelism) $)) | nindent 8 }}
        {{- end }}
      {{- end }}
{{- end }}