{{- if and .Values.prefill .Values.multinode }}
apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: {{ include "llm-d-modelservice.fullname" . }}-prefill
  labels:
    {{- include "llm-d-modelservice.labels" . | nindent 4 }}
    {{- include "llm-d-modelservice.prefilllabels" . | nindent 4 }}
spec:
  {{- if not .Values.prefill.autoscaling.enabled }}
  replicas: {{ default 1 .Values.prefill.replicas }}
  {{- end }}
  leaderWorkerTemplate:
    size: {{ div (int (include "llm-d-modelservice.dataParallelism" .Values.prefill.parallelism)) (int (include "llm-d-modelservice.dataLocalParallelism" .Values.prefill.parallelism)) }}

    # no sidecar so no need to specify leader separately

    workerTemplate:
      metadata:
        labels:
          {{- include "llm-d-modelservice.prefilllabels" . | nindent 10 }}
      spec:
        {{- (include "llm-d-modelservice.modelPod" (merge . (dict "pdSpec" .Values.prefill))) | nindent 6 }}
        {{- with .Values.prefill.containers }}
        containers:
          {{- range . }}
        {{- (include "llm-d-modelservice.container" (merge (dict "role" "prefill" "container" . "parallelism" $.Values.prefill.parallelism) $)) | nindent 8 }}
          {{- end }}
        {{- end }}

{{- end }}
